version: "3.8"

services:
  db :
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: 'technical_test_privy_db'
    ports:
      - "3306:3306"
    volumes:
      - backend_engineer_test_volume:/var/lib/mysql
    networks:
      - backend_engineer_test_network

  backend:
    container_name: cake-api-backend-golang
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=technical_test_privy_db
    image: cake-api-backend-golang:latest
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      - db
    networks:
      - backend_engineer_test_network

networks:
  backend_engineer_test_network: 
    name: backend_engineer_test_network

volumes:
  backend_engineer_test_volume: